### ISSUE TITLE
Allow Keystone v3 Domain Scoped Token

### ISSUE THREAD

**Issue by Carthaca** [flystack/misty#10]
Hi,

currently I can only get a project_scoped token, i.e. omitting `project` / `project_id` to get a domain scoped token does not work.

To decide which authentication version to use in this case, we would need another param, I fear.

Cheers,
Maurice

**Comment by gildub** [comment]
Hi,

Thank you for pointing this, the plan was to be able to use domain scoped authentication.
Just that a little bit more is needed :)

No need to add extra parameter, if a project is provided then project scoped is used otherwise it will fall back to domain scoped. 

The `domain` and `domain_id` parameters are used to specify the scope domain unless using `"default"/"Default"/`.

**Comment by Carthaca** [comment]
Cool, that's not even what I meant :)

I was in the first place stumbling over not being able to select which auth version is being used:
https://github.com/flystack/misty/blob/master/lib/misty/auth.rb#L23

**Comment by gildub** [comment]
Oh I see what you mean, I forgot about that one!!! 

Ok, I think we can still keep the discovery of v2.0 vs v3, well the former is deprecated but we don't want to block it out yet. v2.0 requires a tenant not matter what, otherwise it's v3. Let me reverse the test...

Thank you!

**Comment by Carthaca** [comment]
👍

**Comment by gildub** [comment]
This is available now with v0.4.2. Please reopen if you encounter any issues. Cheers
