### ISSUE TITLE
redundancy in lib/misty/openstack

### ISSUE THREAD

**Issue by Carthaca** [flystack/misty#14]
Hi,

I think the version prefix could be added more generic.

E.g. https://github.com/flystack/misty/blob/master/lib/misty/openstack/glance/glance_v1.rb always starts with `/v1` and https://github.com/flystack/misty/blob/master/lib/misty/openstack/glance/glance_v2.rb always with `/v2`.

The only thing that does not need a version is the version discovery itself (via `GET /`) - maybe this can be handled separately. What do you think?

Cheers

**Comment by gildub** [comment]
Hi Maurice,

The API definitions are generated automatically, besides some fixes, all the definitions are coming straight from the Openstack API-ref. The prefix version is even sometimes, but not necessarily consistently, taken away as we can see with nova [1].

I think it's better to not interfere as much as possible with the API, in order to get more automation.

[1] https://github.com/flystack/misty/blob/master/lib/misty/openstack/nova/nova_v2_1.rb

**Comment by Carthaca** [comment]
Hi Gilles,

I agree, it's better to automate this way.
