### ISSUE TITLE
support for Swift

### ISSUE THREAD

**Issue by majewsky** [flystack/misty#80]
There is `Misty::OpenStack::SwiftV1` already, but from what I can see, it's not really useful because Swift is a bit of an outlier as far as OpenStack APIs go. Request and response bodies always contain objects (i.e. arbitrary binary data) instead of JSON, and all metadata that Misty would deal with is exposed as (or read from) HTTP headers. As far as I can see, at least two changes are required to make Misty useful for Swift clients:

- when talking to Swift...
  - [ ] do not include the `Content-Type: application/json` and `Accept: application/json` headers
  - [ ] do not try to serialize request bodies or parse response bodies as JSON
- extend the API of generated methods to take in a custom set of request headers, which are merged with the standard `Misty::HTTP::Client.headers` upon making the request

Since the last point is useful for other services as well, I've filed it as a separate issue (#81).

**Comment by gildub** [comment]
@majewsky, thank you for looking into Swift.

I realized the prefix filter was missing, so I added https://github.com/flystack/misty/pull/82 .
That allows to properly retrieve containers and objects.

Not all Swift requests are involving an object. Meanwhile when retrieving an object, the ```Content-Type``` doesn't matter because there is no body provided in a GET request. Ultimately the Content-Type header should not be provided at all for requests without a body.

Also, regarding the "Accept" header, that works because even though the client requests an `"Accept": "application/json"` the server cannot provide such format and return the specific value for the content of the file.
For instance, after uploading an image the file can be retrieve, and the returned header shows```"content-type"=>["image/jpeg"]```:
```ruby
File.open('./flower.jpg', 'w') {|f| f.write(osp.object_storage.get_object_content_and_metadata("images", "white-rose-on-the-black-background.jpg").body) }
```
That said I agree that it will be better to provide an Accept header of ```*/*``` when retrieving binary objects. That actually can easily be done by overriding the default corresponding methods.

+1 to be able to provide custom Headers on a per API call basis and not only for Swift.
In the meantime the option ```{ header: "<VALUE>" }``` can be used.

**Comment by majewsky** [comment]
Hi @gildub, thanks for looking into this. I'll leave this issue open until we actually use `Misty::OpenStack::SwiftV1`, but from what I can see, most of our use-case should be covered. RIght now, I have two concerns:

- Since you adjusted `path_prefix_to_ignore`, the requests for accounts, containers and objects should work. But it's not immediately clear to me if `list_activated_capabilities` (the `/info` URL) will also work? The URL for that request is `https://swift.domain.tld/info` even though the endpoint in the catalog looks like `https://swift.domain.tld/v1/AUTH_${PROJECT_ID}`. It's not immediately clear to me that the method builder is able to deduce the former URL correctly from the latter one.

- With #84, I can override `Content-Type: application/json` with some other content type, e.g. `Content-Type: text/plain` when uploading an object. However, is there also a way to completely remove the `Content-Type` header, so that the file type is detected by Swift?

**Comment by gildub** [comment]
@majewsky,

* Re `path_prefix_to_ignore`, when a prefix exists it's removed from the path, since the path for `:list_activated_capabilities` doesn't contain the prefix, the resulting path is unchanged:
```ruby
.../...
# misty 0.9.2
osp = Misty::Cloud.new(auth: auth)
pp osp.object_storage.list_activated_capabilities
# =>{"formpost"=>{},
 "bulk_delete"=>{"max_failed_deletes"=>1000, "max_deletes_per_request"=>10000},
 "container_quotas"=>{},
 "crossdomain"=>{},
 "tempurl"=>
  {"outgoing_remove_headers"=>["x-object-meta-*"],
   "incoming_remove_headers"=>["x-timestamp"],
   "incoming_allow_headers"=>[],
   "methods"=>["GET", "HEAD", "PUT", "POST", "DELETE"],
   "outgoing_allow_headers"=>["x-object-meta-public-*"]},
.../...
```

* Re override header: You're right, and no `Content-Type` at all is better and let the server to handle the request formats. Please see https://github.com/flystack/misty/pull/85

**Comment by gildub** [comment]
@majewsky, this should be addressed with https://github.com/flystack/misty/pull/88. Thanks
