### ISSUE TITLE
extend MethodBuilder to accept custom request headers

### ISSUE THREAD

**Issue by majewsky** [flystack/misty#81]
For several OpenStack APIs, the behavior of individual API requests can be influenced by adding custom request headers. Designate, for instance, recognizes the `X-Auth-All-Projects` and `X-Auth-Sudo-Project-Id` headers to allow superadmins to inspect other project's DNS zones/records; see [documentation here](https://developer.openstack.org/api-ref/dns/) (unfold e.g. the "List Zones" section). My own [Limes](https://github.com/sapcc/limes) accepts the `X-Limes-Cluster-Id` header to select a different OpenStack cluster in multi-cluster deployments.

To cover these usecases, Misty's autogenerated request methods should offer a way for the user to specify custom request headers (at least for the requests that accept them). This is also a necessary pre-requisite for Swift support (see #80), where 90% of the API happens in request/response headers.

**Comment by gildub** [comment]
Custom headers for any request are definitely a must have!

In the meantime a work around is to provide headers though the options of a service. This was actually not properly documented, see https://github.com/flystack/misty/pull/84.

**Comment by hgw77** [comment]
That workarround is not realy working for me because we create at the very beginning a misty object to handle all kinds of requests. So it made no sense to create a brand new misty object when I try to update the metadata for a swift [container ](https://github.com/flystack/misty/blob/master/lib/misty/openstack/swift/swift_v1.rb#L11)or [object](https://github.com/flystack/misty/blob/master/lib/misty/openstack/swift/swift_v1.rb#L20). 

Maybe it is a good idea to have a ``pre_send_request`` function to set the header for the next request? 

for instance:
```ruby   
request_params = {
  "x-container-meta-web-listings"=>false,
  "x-container-meta-quota-count"=>"",
  "x-container-meta-quota-bytes"=>nil,
  "x-versions-location"=>"", 
  "x-container-meta-web-index"=>"",
  "x-container-meta-bla"=>"blub", 
  "x-container-meta-bli"=>"kla"
}
# set additional custom headers for the next request 
misty.object_storage.custom_request_headers(request_params)
#send the request with custom headers
misty.object_storage.create_update_or_delete_container_metadata(container_name)
```
@gildub @majewsky what do you think?

**Comment by majewsky** [comment]
Alternative options:

1. a fluid interface that works with intermediary instances to store the custom headers

```ruby
misty.object_storage.with_headers(request_params).create_container(container_name)
```

2. make MethodBuilder methods recognize a trailing argument that is an instance of a custom headers class (being an instance of the class, rather than an instance of `Hash` is required to distinguish it from query params)

```ruby
misty.object_storage.create_container(container_name, Misty::Headers.new(request_params))
```

**Comment by gildub** [comment]
@hgw77, right it makes no sense to recreate objects, an optional header is needed.

@majewsky, using an intermediary instance for headers is an interesting idea, meanwhile I believe using parser (MethodBuilder) to deal with an trailing and optional header is better because the information (headers) is closer to where it belong (the request). +1 about using a Header(s) class.

**Comment by gildub** [comment]
BTW thank you @hgw77 and @majewsky for bringing this up and your very practical approach to it. Let's see if there are any issues with this so we can address them ASAP. Cheers!

**Comment by hgw77** [comment]
@gildub I thought I let you know that I moved our swift webclient from fog to misty and thanks to your changes and the custom headers everything runs very nicely :-)

**Comment by gildub** [comment]
@hgw77, that's great news, I'm very happy Misty is helping. Thank you for the feedback. From the OpenStack summit and gathering sessions I went to this week I'm confident Misty is a solid approach.
